packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/database-compat@*":
    dependencies:
      "@firebase/app-compat": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/firestore@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/functions@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/storage@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@ionic/react-router@*":
    dependencies:
      "history": "*"
  debug@*:
    dependencies:
      supports-color: "*"
    peerDependenciesMeta:
      supports-color:
        optional: true
  firebase@*:
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-compat": "*"
      "@firebase/auth": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpIgnorePatterns:
  - ./functions/**

yarnPath: .yarn/releases/yarn-3.3.0.cjs
