require_relative '../../.yarn/unplugged/@capacitor-ios-virtual-ef2df37601/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../.yarn/unplugged/@capacitor-ios-virtual-ef2df37601/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../.yarn/unplugged/@capacitor-ios-virtual-ef2df37601/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../.yarn/unplugged/@capacitor-app-virtual-5d5410bcb3/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../.yarn/unplugged/@capacitor-camera-virtual-01519eb5b4/node_modules/@capacitor/camera'
  pod 'CapacitorHaptics', :path => '../../.yarn/unplugged/@capacitor-haptics-virtual-4202f1e63f/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../.yarn/unplugged/@capacitor-keyboard-virtual-de9beb900b/node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../.yarn/unplugged/@capacitor-status-bar-virtual-904d6b75dc/node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
